-- MySQL Workbench Synchronization
-- Generated: 2020-01-08 22:23
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Francisco

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `tsuruvo1_database`.`Imagenes` (
  `_id` INT(11) NOT NULL AUTO_INCREMENT,
  `imagen` TEXT NOT NULL,
  `Categoria` TEXT NOT NULL,
  `Estatus` INT(11) NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  `FechaModificacion` DATE NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
